# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e5a9cab9faa8347b3eb5878487fb1bd4ffd511099016c260a6587d6ea307efb3ff9e4e8fda3ec66d0a6777decc43d3e9a02f05521c4593482253edb49afb0e8

test:
  secret_key_base: 5ddbb5785b78cb8d7e5f07b9672df27aa0b396c7710b42b210a44f522fa4da3b6181ffcc2f1bab1f36a3877aebebe6f5b4fa78de11ee5c013f7b8af16186ea87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
